--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5
-- Dumped by pg_dump version 14.4

-- Started on 2022-10-10 20:48:23

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 222 (class 1259 OID 16684)
-- Name: api_dosis; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_dosis (
    id bigint NOT NULL,
    vacuna character varying(60) NOT NULL,
    fecha_vacuna date NOT NULL,
    dosis_numero smallint NOT NULL,
    empleado_id bigint NOT NULL,
    deleted boolean NOT NULL
);


ALTER TABLE public.api_dosis OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16683)
-- Name: api_dosis_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_dosis ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_dosis_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16676)
-- Name: api_empleado; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_empleado (
    id bigint NOT NULL,
    cedula character varying(10) NOT NULL,
    nombres character varying(100) NOT NULL,
    apellidos character varying(100) NOT NULL,
    email character varying(254) NOT NULL,
    fecha_nacimiento date,
    direccion_domicilio text,
    celular character varying(10),
    vacunado boolean,
    deleted boolean NOT NULL,
    user_id bigint
);


ALTER TABLE public.api_empleado OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16675)
-- Name: api_empleado_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_empleado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_empleado_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16690)
-- Name: api_userprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_userprofile (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(255),
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(255) NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL
);


ALTER TABLE public.api_userprofile OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16702)
-- Name: api_userprofile_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_userprofile_groups (
    id bigint NOT NULL,
    userprofile_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.api_userprofile_groups OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16701)
-- Name: api_userprofile_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_userprofile_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_userprofile_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16689)
-- Name: api_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16708)
-- Name: api_userprofile_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.api_userprofile_user_permissions (
    id bigint NOT NULL,
    userprofile_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.api_userprofile_user_permissions OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16707)
-- Name: api_userprofile_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.api_userprofile_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.api_userprofile_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16636)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16635)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 16644)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16643)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 214 (class 1259 OID 16630)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- TOC entry 213 (class 1259 OID 16629)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16770)
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 16750)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16749)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 212 (class 1259 OID 16622)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- TOC entry 211 (class 1259 OID 16621)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 210 (class 1259 OID 16614)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- TOC entry 209 (class 1259 OID 16613)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16783)
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- TOC entry 3251 (class 2606 OID 16688)
-- Name: api_dosis api_dosis_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_dosis
    ADD CONSTRAINT api_dosis_pkey PRIMARY KEY (id);


--
-- TOC entry 3246 (class 2606 OID 16682)
-- Name: api_empleado api_empleado_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_empleado
    ADD CONSTRAINT api_empleado_pkey PRIMARY KEY (id);


--
-- TOC entry 3248 (class 2606 OID 16798)
-- Name: api_empleado api_empleado_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_empleado
    ADD CONSTRAINT api_empleado_user_id_key UNIQUE (user_id);


--
-- TOC entry 3254 (class 2606 OID 16700)
-- Name: api_userprofile api_userprofile_email_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_userprofile
    ADD CONSTRAINT api_userprofile_email_key UNIQUE (email);


--
-- TOC entry 3259 (class 2606 OID 16706)
-- Name: api_userprofile_groups api_userprofile_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_userprofile_groups
    ADD CONSTRAINT api_userprofile_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 3262 (class 2606 OID 16722)
-- Name: api_userprofile_groups api_userprofile_groups_userprofile_id_group_id_f2d1b2f8_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_userprofile_groups
    ADD CONSTRAINT api_userprofile_groups_userprofile_id_group_id_f2d1b2f8_uniq UNIQUE (userprofile_id, group_id);


--
-- TOC entry 3256 (class 2606 OID 16696)
-- Name: api_userprofile api_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_userprofile
    ADD CONSTRAINT api_userprofile_pkey PRIMARY KEY (id);


--
-- TOC entry 3264 (class 2606 OID 16736)
-- Name: api_userprofile_user_permissions api_userprofile_user_per_userprofile_id_permissio_791df516_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_userprofile_user_permissions
    ADD CONSTRAINT api_userprofile_user_per_userprofile_id_permissio_791df516_uniq UNIQUE (userprofile_id, permission_id);


--
-- TOC entry 3267 (class 2606 OID 16712)
-- Name: api_userprofile_user_permissions api_userprofile_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_userprofile_user_permissions
    ADD CONSTRAINT api_userprofile_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 3236 (class 2606 OID 16673)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 3241 (class 2606 OID 16659)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 3244 (class 2606 OID 16648)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 3238 (class 2606 OID 16640)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 3231 (class 2606 OID 16650)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 3233 (class 2606 OID 16634)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 3275 (class 2606 OID 16774)
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- TOC entry 3277 (class 2606 OID 16776)
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- TOC entry 3271 (class 2606 OID 16757)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 3226 (class 2606 OID 16628)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 3228 (class 2606 OID 16626)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 3224 (class 2606 OID 16620)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 3280 (class 2606 OID 16789)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 3249 (class 1259 OID 16718)
-- Name: api_dosis_empleado_id_c292d184; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_dosis_empleado_id_c292d184 ON public.api_dosis USING btree (empleado_id);


--
-- TOC entry 3252 (class 1259 OID 16720)
-- Name: api_userprofile_email_6279d7da_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_userprofile_email_6279d7da_like ON public.api_userprofile USING btree (email varchar_pattern_ops);


--
-- TOC entry 3257 (class 1259 OID 16734)
-- Name: api_userprofile_groups_group_id_4bbb714d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_userprofile_groups_group_id_4bbb714d ON public.api_userprofile_groups USING btree (group_id);


--
-- TOC entry 3260 (class 1259 OID 16733)
-- Name: api_userprofile_groups_userprofile_id_c604c343; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_userprofile_groups_userprofile_id_c604c343 ON public.api_userprofile_groups USING btree (userprofile_id);


--
-- TOC entry 3265 (class 1259 OID 16748)
-- Name: api_userprofile_user_permissions_permission_id_f8a7bcee; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_userprofile_user_permissions_permission_id_f8a7bcee ON public.api_userprofile_user_permissions USING btree (permission_id);


--
-- TOC entry 3268 (class 1259 OID 16747)
-- Name: api_userprofile_user_permissions_userprofile_id_6c285edb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX api_userprofile_user_permissions_userprofile_id_6c285edb ON public.api_userprofile_user_permissions USING btree (userprofile_id);


--
-- TOC entry 3234 (class 1259 OID 16674)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 3239 (class 1259 OID 16670)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 3242 (class 1259 OID 16671)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 3229 (class 1259 OID 16656)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 3273 (class 1259 OID 16782)
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- TOC entry 3269 (class 1259 OID 16768)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 3272 (class 1259 OID 16769)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 3278 (class 1259 OID 16791)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 3281 (class 1259 OID 16790)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 3286 (class 2606 OID 16713)
-- Name: api_dosis api_dosis_empleado_id_c292d184_fk_api_empleado_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_dosis
    ADD CONSTRAINT api_dosis_empleado_id_c292d184_fk_api_empleado_id FOREIGN KEY (empleado_id) REFERENCES public.api_empleado(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3285 (class 2606 OID 16804)
-- Name: api_empleado api_empleado_user_id_df8f2716_fk_api_userprofile_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_empleado
    ADD CONSTRAINT api_empleado_user_id_df8f2716_fk_api_userprofile_id FOREIGN KEY (user_id) REFERENCES public.api_userprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3287 (class 2606 OID 16723)
-- Name: api_userprofile_groups api_userprofile_grou_userprofile_id_c604c343_fk_api_userp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_userprofile_groups
    ADD CONSTRAINT api_userprofile_grou_userprofile_id_c604c343_fk_api_userp FOREIGN KEY (userprofile_id) REFERENCES public.api_userprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3288 (class 2606 OID 16728)
-- Name: api_userprofile_groups api_userprofile_groups_group_id_4bbb714d_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_userprofile_groups
    ADD CONSTRAINT api_userprofile_groups_group_id_4bbb714d_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3290 (class 2606 OID 16742)
-- Name: api_userprofile_user_permissions api_userprofile_user_permission_id_f8a7bcee_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_userprofile_user_permissions
    ADD CONSTRAINT api_userprofile_user_permission_id_f8a7bcee_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3289 (class 2606 OID 16737)
-- Name: api_userprofile_user_permissions api_userprofile_user_userprofile_id_6c285edb_fk_api_userp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.api_userprofile_user_permissions
    ADD CONSTRAINT api_userprofile_user_userprofile_id_6c285edb_fk_api_userp FOREIGN KEY (userprofile_id) REFERENCES public.api_userprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3284 (class 2606 OID 16665)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3283 (class 2606 OID 16660)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3282 (class 2606 OID 16651)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3293 (class 2606 OID 16777)
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_api_userprofile_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_api_userprofile_id FOREIGN KEY (user_id) REFERENCES public.api_userprofile(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3291 (class 2606 OID 16758)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3292 (class 2606 OID 16763)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_api_userprofile_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_api_userprofile_id FOREIGN KEY (user_id) REFERENCES public.api_userprofile(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2022-10-10 20:48:23

--
-- PostgreSQL database dump complete
--

